-- MySQL Script generated by MySQL Workbench
-- Sun Mar 16 20:36:05 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema backend713
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema backend713
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `backend713` DEFAULT CHARACTER SET utf8 ;
USE `backend713` ;

-- -----------------------------------------------------
-- Table `backend713`.`academic_position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backend713`.`academic_position` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `academic_position_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `backend713`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backend713`.`admin` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(65) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `backend713`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backend713`.`department` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `initials` VARCHAR(255) NOT NULL,
  `department_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `initials_UNIQUE` (`initials` ASC),
  UNIQUE INDEX `department_name_UNIQUE` (`department_name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `backend713`.`advisor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backend713`.`advisor` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `picture` VARCHAR(45) NOT NULL,
  `usename` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `Academic_position_id` INT(11) NOT NULL,
  `Department_id` INT(11) NOT NULL,
  `Admin_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `Admin_id`, `Department_id`, `Academic_position_id`),
  UNIQUE INDEX `usename_UNIQUE` (`usename` ASC),
  INDEX `fk_Advisor_Academic_position_idx` (`Academic_position_id` ASC),
  INDEX `fk_Advisor_Department1_idx` (`Department_id` ASC),
  INDEX `fk_Advisor_Admin1_idx` (`Admin_id` ASC),
  CONSTRAINT `fk_Advisor_Academic_position`
    FOREIGN KEY (`Academic_position_id`)
    REFERENCES `backend713`.`academic_position` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Advisor_Admin1`
    FOREIGN KEY (`Admin_id`)
    REFERENCES `backend713`.`admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Advisor_Department1`
    FOREIGN KEY (`Department_id`)
    REFERENCES `backend713`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `backend713`.`degree`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backend713`.`degree` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `degree_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `backend713`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backend713`.`student` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `student_id_card` VARCHAR(15) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `picture` VARCHAR(45) NOT NULL,
  `usename` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `Department_id` INT(11) NOT NULL,
  `Degree_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `Department_id`, `Degree_id`),
  UNIQUE INDEX `student_id_card_UNIQUE` (`student_id_card` ASC),
  UNIQUE INDEX `usename_UNIQUE` (`usename` ASC),
  INDEX `fk_Student_Department1_idx` (`Department_id` ASC),
  INDEX `fk_Student_Degree1_idx` (`Degree_id` ASC),
  CONSTRAINT `fk_Student_Degree1`
    FOREIGN KEY (`Degree_id`)
    REFERENCES `backend713`.`degree` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_Department1`
    FOREIGN KEY (`Department_id`)
    REFERENCES `backend713`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `backend713`.`admin_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backend713`.`admin_log` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `action` VARCHAR(255) NOT NULL,
  `Student_id` INT(11) NOT NULL,
  `Advisor_id` INT(11) NOT NULL,
  `Admin_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `Admin_id`, `Advisor_id`, `Student_id`),
  INDEX `fk_Admin_log_Student1_idx` (`Student_id` ASC),
  INDEX `fk_Admin_log_Advisor1_idx` (`Advisor_id` ASC),
  INDEX `fk_Admin_log_Admin1_idx` (`Admin_id` ASC),
  CONSTRAINT `fk_Admin_log_Admin1`
    FOREIGN KEY (`Admin_id`)
    REFERENCES `backend713`.`admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Admin_log_Advisor1`
    FOREIGN KEY (`Advisor_id`)
    REFERENCES `backend713`.`advisor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Admin_log_Student1`
    FOREIGN KEY (`Student_id`)
    REFERENCES `backend713`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `backend713`.`announcement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backend713`.`announcement` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `topic` VARCHAR(70) NOT NULL,
  `description` VARCHAR(225) NOT NULL,
  `file` VARCHAR(45) NULL DEFAULT NULL,
  `posted_date` DATETIME NOT NULL,
  `Advisor_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `Advisor_id`),
  INDEX `fk_Announcement_Advisor1_idx` (`Advisor_id` ASC),
  CONSTRAINT `fk_Announcement_Advisor1`
    FOREIGN KEY (`Advisor_id`)
    REFERENCES `backend713`.`advisor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `backend713`.`status_appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backend713`.`status_appointment` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `backend713`.`appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backend713`.`appointment` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `topic` VARCHAR(70) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `requested_date` DATETIME NOT NULL,
  `appointment_request_date_time` DATETIME NOT NULL,
  `student_confirmation` TINYINT(4) NOT NULL,
  `Student_id` INT(11) NOT NULL,
  `Advisor_id` INT(11) NOT NULL,
  `Status_appointment_id` INT(11) NOT NULL,
  `Admin_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `Advisor_id`, `Student_id`, `Status_appointment_id`),
  INDEX `fk_Appointment_Student1_idx` (`Student_id` ASC),
  INDEX `fk_Appointment_Advisor1_idx` (`Advisor_id` ASC),
  INDEX `fk_Appointment_Status_appointment1_idx` (`Status_appointment_id` ASC),
  INDEX `fk_Appointment_Admin1_idx` (`Admin_id` ASC),
  CONSTRAINT `fk_Appointment_Admin1`
    FOREIGN KEY (`Admin_id`)
    REFERENCES `backend713`.`admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appointment_Advisor1`
    FOREIGN KEY (`Advisor_id`)
    REFERENCES `backend713`.`advisor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appointment_Status_appointment1`
    FOREIGN KEY (`Status_appointment_id`)
    REFERENCES `backend713`.`status_appointment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appointment_Student1`
    FOREIGN KEY (`Student_id`)
    REFERENCES `backend713`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `backend713`.`responder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backend713`.`responder` (
  `id` INT(11) NOT NULL,
  `responder` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `backend713`.`feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backend713`.`feedback` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `feedback` VARCHAR(255) NULL DEFAULT NULL,
  `timesteamp` DATETIME NULL DEFAULT NULL,
  `Student_id` INT(11) NOT NULL,
  `Advisor_id` INT(11) NOT NULL,
  `Responder_id` INT(11) NOT NULL,
  `Admin_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `Student_id`, `Advisor_id`, `Responder_id`),
  INDEX `fk_FeedBack_Student1_idx` (`Student_id` ASC),
  INDEX `fk_FeedBack_Advisor1_idx` (`Advisor_id` ASC),
  INDEX `fk_FeedBack_Responder1_idx` (`Responder_id` ASC),
  INDEX `fk_FeedBack_Admin1_idx` (`Admin_id` ASC),
  CONSTRAINT `fk_FeedBack_Admin1`
    FOREIGN KEY (`Admin_id`)
    REFERENCES `backend713`.`admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FeedBack_Advisor1`
    FOREIGN KEY (`Advisor_id`)
    REFERENCES `backend713`.`advisor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FeedBack_Responder1`
    FOREIGN KEY (`Responder_id`)
    REFERENCES `backend713`.`responder` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FeedBack_Student1`
    FOREIGN KEY (`Student_id`)
    REFERENCES `backend713`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
